//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemReserved.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemReserved.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a FrameworkFolders entity according to the specified directories paths.
        /// </summary>
        public static string BuildFrameworkFolders_Description {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build FrameworkFolders.
        /// </summary>
        public static string BuildFrameworkFolders_DisplayName {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the directory to be used for exception screenshots.
        ///The default value is &apos;Exceptions_Screenshots&apos;.
        /// </summary>
        public static string BuildFrameworkFolders_ExScreenshotsFolder_Description {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_ExScreenshotsFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExScreenshots Folder.
        /// </summary>
        public static string BuildFrameworkFolders_ExScreenshotsFolder_DisplayName {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_ExScreenshotsFolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FrameworkFolders entity.
        /// </summary>
        public static string BuildFrameworkFolders_FrameworkFolders_Description {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_FrameworkFolders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameworkFolders.
        /// </summary>
        public static string BuildFrameworkFolders_FrameworkFolders_DisplayName {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_FrameworkFolders_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the directory to be used for input files.
        ///The default value is &apos;Data\Input&apos;.
        /// </summary>
        public static string BuildFrameworkFolders_InputFolder_Description {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_InputFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Folder.
        /// </summary>
        public static string BuildFrameworkFolders_InputFolder_DisplayName {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_InputFolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the directory to be used for output files.
        ///The default value is &apos;Data\Output&apos;.
        /// </summary>
        public static string BuildFrameworkFolders_OutputFolder_Description {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_OutputFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string BuildFrameworkFolders_OutputFolder_DisplayName {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_OutputFolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the directory to be used for report files.
        ///The default value is &apos;Data\Reports&apos;.
        /// </summary>
        public static string BuildFrameworkFolders_ReportsFolder_Description {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_ReportsFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Folder.
        /// </summary>
        public static string BuildFrameworkFolders_ReportsFolder_DisplayName {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_ReportsFolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the directory to be used for temporal files.
        ///The default value is &apos;Data\Temp&apos;.
        /// </summary>
        public static string BuildFrameworkFolders_TempFolder_Description {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_TempFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Folder.
        /// </summary>
        public static string BuildFrameworkFolders_TempFolder_DisplayName {
            get {
                return ResourceManager.GetString("BuildFrameworkFolders_TempFolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial value for ContinuousRetryNumber.
        /// </summary>
        public static string BuildSystemReserved_ContinuousRetryNumber_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_ContinuousRetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Retry Number.
        /// </summary>
        public static string BuildSystemReserved_ContinuousRetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_ContinuousRetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dictionary with desired custom parameters defined at runtime.
        /// </summary>
        public static string BuildSystemReserved_CustomParameters_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_CustomParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Parameters.
        /// </summary>
        public static string BuildSystemReserved_CustomParameters_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_CustomParameters_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a SystemReserved entity according to the specified parameters.
        /// </summary>
        public static string BuildSystemReserved_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build SystemReserved.
        /// </summary>
        public static string BuildSystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FrameworkFolders entity.
        /// </summary>
        public static string BuildSystemReserved_Folders_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_Folders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string BuildSystemReserved_Folders_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_Folders_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial value for InitRetryNumber .
        /// </summary>
        public static string BuildSystemReserved_InitRetryNumber_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_InitRetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init Retry Number.
        /// </summary>
        public static string BuildSystemReserved_InitRetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_InitRetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the framework uses queues.
        /// </summary>
        public static string BuildSystemReserved_IsQueueItem_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_IsQueueItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Queue Item.
        /// </summary>
        public static string BuildSystemReserved_IsQueueItem_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_IsQueueItem_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial value for RetryNumber.
        /// </summary>
        public static string BuildSystemReserved_RetryNumber_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_RetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Number.
        /// </summary>
        public static string BuildSystemReserved_RetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_RetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemReserved entity.
        /// </summary>
        public static string BuildSystemReserved_SystemReserved_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_SystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemReserved.
        /// </summary>
        public static string BuildSystemReserved_SystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_SystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial value for TransactionNumber.
        /// </summary>
        public static string BuildSystemReserved_TransactionNumber_Description {
            get {
                return ResourceManager.GetString("BuildSystemReserved_TransactionNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Number.
        /// </summary>
        public static string BuildSystemReserved_TransactionNumber_DisplayName {
            get {
                return ResourceManager.GetString("BuildSystemReserved_TransactionNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increments ContinuousRetryNumber in 1.
        /// </summary>
        public static string IncrementContinuousRetryNumber_Description {
            get {
                return ResourceManager.GetString("IncrementContinuousRetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Continuous Retry Number.
        /// </summary>
        public static string IncrementContinuousRetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("IncrementContinuousRetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemReserved entity.
        /// </summary>
        public static string IncrementContinuousRetryNumber_SystemReserved_Description {
            get {
                return ResourceManager.GetString("IncrementContinuousRetryNumber_SystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemReserved.
        /// </summary>
        public static string IncrementContinuousRetryNumber_SystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("IncrementContinuousRetryNumber_SystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increments InitRetryNumber in 1.
        /// </summary>
        public static string IncrementInitRetryNumber_Description {
            get {
                return ResourceManager.GetString("IncrementInitRetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Init Retry Number.
        /// </summary>
        public static string IncrementInitRetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("IncrementInitRetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemReserved entity.
        /// </summary>
        public static string IncrementInitRetryNumber_SystemReserved_Description {
            get {
                return ResourceManager.GetString("IncrementInitRetryNumber_SystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemReserved.
        /// </summary>
        public static string IncrementInitRetryNumber_SystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("IncrementInitRetryNumber_SystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increments RetryNumber in 1.
        /// </summary>
        public static string IncrementRetryNumber_Description {
            get {
                return ResourceManager.GetString("IncrementRetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Retry Number.
        /// </summary>
        public static string IncrementRetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("IncrementRetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemReserved entity.
        /// </summary>
        public static string IncrementRetryNumber_SystemReserved_Description {
            get {
                return ResourceManager.GetString("IncrementRetryNumber_SystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemReserved.
        /// </summary>
        public static string IncrementRetryNumber_SystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("IncrementRetryNumber_SystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increments TransactionNumber in 1.
        /// </summary>
        public static string IncrementTransactionNumber_Description {
            get {
                return ResourceManager.GetString("IncrementTransactionNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Transaction Number.
        /// </summary>
        public static string IncrementTransactionNumber_DisplayName {
            get {
                return ResourceManager.GetString("IncrementTransactionNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemReserved entity.
        /// </summary>
        public static string IncrementTransactionNumber_SystemReserved_Description {
            get {
                return ResourceManager.GetString("IncrementTransactionNumber_SystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemReserved.
        /// </summary>
        public static string IncrementTransactionNumber_SystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("IncrementTransactionNumber_SystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets ContinuousRetryNumber to 0.
        /// </summary>
        public static string ResetConinuousRetryNumber_Description {
            get {
                return ResourceManager.GetString("ResetConinuousRetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Continuous Retry Number.
        /// </summary>
        public static string ResetConinuousRetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("ResetConinuousRetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemReserved entity.
        /// </summary>
        public static string ResetConinuousRetryNumber_SystemReserved_Description {
            get {
                return ResourceManager.GetString("ResetConinuousRetryNumber_SystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemReserved.
        /// </summary>
        public static string ResetConinuousRetryNumber_SystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("ResetConinuousRetryNumber_SystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets InitRetryNumber to 0.
        /// </summary>
        public static string ResetInitRetryNumber_Description {
            get {
                return ResourceManager.GetString("ResetInitRetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Init Retry Number.
        /// </summary>
        public static string ResetInitRetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("ResetInitRetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemReserved entity.
        /// </summary>
        public static string ResetInitRetryNumber_SystemReserved_Description {
            get {
                return ResourceManager.GetString("ResetInitRetryNumber_SystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemReserved.
        /// </summary>
        public static string ResetInitRetryNumber_SystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("ResetInitRetryNumber_SystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets RetryNumber to 0.
        /// </summary>
        public static string ResetRetryNumber_Description {
            get {
                return ResourceManager.GetString("ResetRetryNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Retry Number.
        /// </summary>
        public static string ResetRetryNumber_DisplayName {
            get {
                return ResourceManager.GetString("ResetRetryNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SystemReserved entity.
        /// </summary>
        public static string ResetRetryNumber_SystemReserved_Description {
            get {
                return ResourceManager.GetString("ResetRetryNumber_SystemReserved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemReserved.
        /// </summary>
        public static string ResetRetryNumber_SystemReserved_DisplayName {
            get {
                return ResourceManager.GetString("ResetRetryNumber_SystemReserved_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
